on:
  push:
    branches:
      - main

name: Build and Deploy Content Repo Branch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
          repo: EI2030
          event_type: content_repo_deploy
